language: java

sudo: required

jdk:
  - oraclejdk8

before_script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version

script: mvn clean test

after_success:
  - mvn clean test jacoco:report coveralls:report
